name: renovateNodeCICD
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: install action
        uses: actions/checkout@v5

      - name: docker && docker compose check
        run:
          docker -v
          docker compose version

      - name: docker up
        run: docker compose up -d

      - name: check compose with renovate
        uses: renovatebot/github-action@v46.1.16
        with:
          token: ${{ secrets.RENOVATE }}
        env:
          LOG_LEVEL: "debug"
          RENOVATE_REPOSITORIES: "LiliSoli/renovateNodeCICD"

      - name: Clean container
        if: always()
        run: docker compose down

